# Site settings
title: Zachary A. McGee
email: zmcgee@stlawu.edu
description: > # this means to ignore newlines until "baseurl:"
  I am an Assistant Professor in the Department of Government at St. Lawrence University.
  My research and teaching interests include American political institutions, with a focus on the U.S. Congress, public policy, with a focus on decision-making and network analysis, and political parties, with a focus on intraparty factions.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://zacharymcgee.net" # the base hostname & protocol for your site
googlescholar: https://scholar.google.com/citations?user=wlRQLtwAAAAJ&hl=en
orcid: https://orcid.org/0000-0002-2462-0269
github_username:  zacmcgee
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
